name: Emergent Session Request
description: Please submit your request for an emergent session. We will get back to you as soon as possible.
title: "[Emergent Session]: "
labels: ["emergent sessions", "urgent"]
assignees:
  - ["juchiyu", "jdkent"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for submitting an emergent session request!
  - type: input
    id: name
    attributes:
      label: Host and Affiliation
      description: Who are you and what is your affiliation?
      placeholder: e.g., "Jane Doe, Organization or University"
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: input
    id: volunteer
    attributes:
      label: Recording and streaming volunteer
      description: Who can help with recording and streaming the session from your team?
      placeholder: e.g., "Name, email address"
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Short description and the goals for the session
      description: Please provide a short description of the session and what you hope to achieve.
      placeholder: insert a short description of the session and what you hope to achieve
    validations:
      required: true
  - type: textarea
    id: links
    attributes:
      label: Useful links
      description: Please provide links to any relevant materials (e.g., website, repo, slides, papers, etc.)
      placeholder: Please enter NA if not applicable
    validations:
      required: true
  - type: dropdown
    id: time
    attributes:
      label: Which time slots work for you? (Please select all that apply.)
      description: We will confirm the time slot with you, but please be aware that the availability might change based on other submissions.
      multiple: true
      options: 
        - Ses 1 - 9:15-10:15 (GMT+10) June 25 (Wednesday)
        - Ses 2 - 15:30-16:30 (GMT+10) June 25 (Wednesday)
        - Ses 3 - 17:45-18:45 (GMT+10) June 25 (Wednesday)
        - Ses 4 - 9:15-10:15 (GMT+10) June 26 (Thursday)
        - Ses 5 - 11:30-12:30 (GMT+10) June 26 (Thursday)
        - Ses 6 - 9:15-10:15 (GMT+10) June 27 (Friday)
        - Ses 7 - 11:30-12:30 (GMT+10) June 27 (Friday)
        - Ses 8 - 9:15-10:15 (GMT+10) June 28 (Saturday)
        - Ses 9 - 11:30-12:30 (GMT+10) June 28 (Saturday)
      default: 0
    validations:
      required: true
  - type: textarea
    id: github
    attributes:
      label: Relevant GitHub Users
      description: Please @ the GitHub usernames of people you wish to include.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Agreement to Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://ohbm.github.io/osr2025/osr_coc/).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - type: checkboxes
    id: share
    attributes:
      label: Agreement to Recording and Disemmination
      description: By submitting this issue, you agree to let us record the session and upload it our YouTube channel.
      options:
        - label: I agree to record and diseminate this session on YouTube.
          required: true
  - type: checkboxes
    id: proceedings
    attributes:
      label: Agreement to be inclued in the proceedings
      description: By submitting this issue, you agree to let us transcribe the session into our proceeding. 
      options:
        - label: I agree to be included in the proceedings.
          required: true